### ISSUE TITLE
无法关闭夜间模式

### ISSUE THREAD

**Issue by ershiwo** [ekibun/Bangumi#1]
手机&系统：Nokia 7 plus，Android Pie
软件版本：alpha20181114 至 alpha20190217

问题描述：应用打开时永远是默认夜间模式，主题切换开关在第一次按下时无效，第二次切换时才能切换到白天模式，并且不能保存此状态。

**Comment by ekibun** [comment]
默认是夜间模式吗？（可能默认是随系统换吧
再下一遍alpha20190217试试

**Comment by ershiwo** [comment]
没有，不是随系统主题（我自己设置的浅色主题）。新 release 目前解决了问题，谢谢~

来自 Outlook for Android<https://aka.ms/ghei36>

________________________________
