### ISSUE TITLE
显示bug&章节标记bug

### ISSUE THREAD

**Issue by RtYkk** [ekibun/Bangumi#15]
[【未解决】求证？石立太一现在已经是董事（取締役）了？ ](https://bgm.tv/group/topic/354655) 

这帖子的三楼的第一行我用两部手机看了看都是空白的

> 

就是上面这一句🤔

**Comment by RtYkk** [comment]
不想开新的了，现在长按一个章节，然后选看到好像会直接看过全集而不是看到我选中的那一集

**Comment by ekibun** [comment]
github的markdown是支持html语法的。。
修了，但是感觉\[code]会有问题，懒得管了

**Comment by RtYkk** [comment]
> github的markdown是支持html语法的。。
> 修了，但是感觉[code]会有问题，懒得管了

code好像没事
