### ISSUE TITLE
吐槽加载循环bug

### ISSUE THREAD

**Issue by Bubbleioa** [ekibun/Bangumi#16]
就是下拉吐槽（全站）的时候会一直重复一个片段的消息
![8eUCwt.gif](https://s1.ax1x.com/2020/03/12/8eUCwt.gif)

**Comment by Bubbleioa** [comment]
https://s1.ax1x.com/2020/03/12/8eUCwt.gif

**Comment by ekibun** [comment]
才发现全站本身只有一页。加了个到底了的提示。
