### ISSUE TITLE
login failed

### ISSUE THREAD

**Issue by Laurenfrost** [ekibun/Bangumi#18]
进入app后选择”点击头像登录“，打开登录页面；在登陆页面登陆成功后，返回到app主界面弹出提示”login failed“。app内相关功能确实因为未登录无法使用。经反复尝试登陆后无果，重新安装未有改善。  
恳请帮助，万分感激。  
  
另，因为网络直连状态下相关页面无法打开，遇到上述情况时有使用V2Ray代理功能。

**Comment by ekibun** [comment]
没法复现，如果能拿到log最好了

或者先试试多用户之前的[这个版本](https://github.com/ekibun/Bangumi/releases/tag/alpha20200312)

**Comment by Laurenfrost** [comment]
感谢您的善意解答，这个log应该在哪找？  
旧版本我也尝试一下。

**Comment by ekibun** [comment]
试试[这个](https://github.com/ekibun/BangumiLogcatPlugin/releases/tag/init)，assert的两个apk都装上，然后点开侧边抽屉的调试日志，操作完把开关关掉会弹出分享文件，把文件发过来我看看

**Comment by Laurenfrost** [comment]
非常感谢。log文件在[这里](https://github.com/Laurenfrost/storage/blob/master/logcat)

**Comment by ekibun** [comment]
抱歉没能发现问题在哪。从右上角的收件箱打开webview登录，操作一下再返回试试看

**Comment by Laurenfrost** [comment]
从收件箱打开webview登录就好了

**Comment by Laurenfrost** [comment]
我重新操作了一遍：从正常的登录打开web登录--失败--从收件箱登录--成功。[log文件](https://github.com/Laurenfrost/storage/blob/master/logcat(1))

**Comment by ekibun** [comment]
试试这个看看能不能解决，logcat可能包含cookie信息，请在操作之后在webview里手动登出一下
[app-github-release.zip](https://github.com/ekibun/Bangumi/files/4418896/app-github-release.zip)

**Comment by Laurenfrost** [comment]
该版本情况跟之前一样，没有变化。我进行了跟之前同样的操作，[logcat文件](https://github.com/Laurenfrost/storage/blob/master/logcat(2))。谢谢您的提醒。  
  
其实我觉得可能主要还是我手机的锅（用了5年了）不过既然可以从收件箱登录，某种程度上来说也算是问题解决了吧。您要是比较忙的话，就把这个issue关了吧，反正能用了。  
当然您要是有兴趣继续研究这个问题的话，我这边自然是乐意奉陪。  
  
无论如何，谢谢您的帮助。

**Comment by ekibun** [comment]
那再试试这个，现在没拿到cookie不会关闭页面，试试看登录之后页面能不能自动关闭
[app-github-release.zip](https://github.com/ekibun/Bangumi/files/4419108/app-github-release.zip)

**Comment by Laurenfrost** [comment]
该版本情况和之前一样。  
  
不过我不确定您说的“没拿到cookie不会关闭页面”的这个”关闭页面“是个什么情况。  
从我的视角来看，我的登录操作流程是这样的：
1. 点击头像（阿卡林）所在的位置；
2. 打开了Webview里面是登录界面；
3. 输入账户信息并点击登录；
4. Webview中进入了bangumi的登陆后页面（“欢迎使用 Bangumi 管理收视进度”）；
5. 我点击左上角的返回箭头，关闭了Webwiew回到了app的界面；
6. 提示login failed。  
  
Webview中进入“欢迎使用 Bangumi 管理收视进度”的页面之后并不会自动关闭这个Webview，一直以来都是这样的。

**Comment by ekibun** [comment]
麻烦再试试这个，里面录了一个正常登录的视频，请对照看看，也麻烦记录一下log
[release.zip](https://github.com/ekibun/Bangumi/files/4419234/release.zip)

**Comment by Laurenfrost** [comment]
确实是这样，在我的手机上登陆后Webview不会自动关闭。等多久都不行。  
[这个](https://github.com/Laurenfrost/storage/blob/master/logcat(3))是上一次忘发的log。  
[这个](https://github.com/Laurenfrost/storage/blob/master/logcat(5))是这次的log。

**Comment by ekibun** [comment]
很奇怪，试试看这个版本，登录的时候点一下其他页面，看看会不会跳回登录页面
[app-github-release.zip](https://github.com/ekibun/Bangumi/files/4419911/app-github-release.zip)

**Comment by Laurenfrost** [comment]
太强了，这个版本点登录后Webview就自动关闭，app也能正常使用了。[log文件](https://github.com/Laurenfrost/storage/blob/master/logcat(6))
