### ISSUE TITLE
全站动态无法正常翻页。

### ISSUE THREAD

**Issue by RtYkk** [ekibun/Bangumi#19]
难得看看全站动态，发现翻了一点就没有下一页了…显示没有更多数据。自己和好友没有这个问题

**Comment by ekibun** [comment]
全站动态拿不到下一页

**Comment by RtYkk** [comment]
![chrome_joJc24qNPJ](https://user-images.githubusercontent.com/45971730/80556156-437daa00-8a05-11ea-8ddd-308b15581328.png)
确实，这是什么设定啊，好难受。
