### ISSUE TITLE
图片无法正常显示（比较玄学）

### ISSUE THREAD

**Issue by RtYkk** [ekibun/Bangumi#21]
qq被保护模式了该怎么解…… https://bgm.tv/group/topic/356300
主楼图片无法正常显示，浏览器没有任何问题。app内无论是梯与不梯都不行，怀疑是图片中带有中文的问题？但是经过我的实测又不是…

https://p.sda1.dev/0/d556cf378d7ac45c3e73998fd0a824e8/截图.png

https://p.sda1.dev/0/a3ca747406dddf89d07c19a01a87e486/截图163628262739172啊啊啊7374_____.png

加长路径也无法复现，难道我是个案？

**Comment by RtYkk** [comment]
非个案，已知图片链接中夹带空格就会解析失败。

**Comment by ekibun** [comment]
done
