### ISSUE TITLE
动画条目无法同步

### ISSUE THREAD

**Issue by Autumn-of-One** [ekibun/Bangumi#3]
在动画条目《人形电脑天使心》中出现了问题，无论我在网页或者APP里进行怎样的操作，在APP主界面“收藏-在看”栏里，只显示“看到第一话”

**Comment by ekibun** [comment]
是日期规则的问题了，最近加了按时间排序，要不还是删掉吧。
《人形电脑天使心》 只有第一集是2002-04-03这种格式的，其他的都是10.04.2002

**Comment by Autumn-of-One** [comment]
明白了
