### ISSUE TITLE
开发者您好，能增加个状态栏沉浸

### ISSUE THREAD

**Issue by Tartarus2014** [ekibun/Bangumi#30]
![Screenshot_20240204_143401_Bangumi](https://github.com/ekibun/Bangumi/assets/39802246/5a4dc010-0c6e-467b-bd1c-811dcddebfce)

目前在三星上没法沉浸，开发者能否加个状态栏沉浸。

**Comment by ekibun** [comment]
试了一下这插件还能用 https://github.com/ekibun/BangumiThemePlugin/releases/tag/init

**Comment by Tartarus2014** [comment]
> 试了一下这个插件还能用https://github.com/ekibun/BangumiThemePlugin/releases/tag/init

这个确实可以 谢谢
