### ISSUE TITLE
进入条目时报错 SSLHandshakeException

### ISSUE THREAD

**Issue by ovrase** [ekibun/Bangumi#4]
MIX2S Android 9
alpha20190626

_javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found._

![photo_2019-07-13_17-42-12](https://user-images.githubusercontent.com/22218428/61169967-9204a980-a595-11e9-991b-89c534476f45.jpg)

**Comment by ekibun** [comment]
网络错误都会显示在下面，重进或者刷新就好了

**Comment by ovrase** [comment]
> 网络错误都会显示在下面，重进或者刷新就好了

这是100%复现的错误，在移动数据和联通宽带均会出现
