### ISSUE TITLE
打不开索引

### ISSUE THREAD

**Issue by SilenceContempt** [ekibun/Bangumi#5]
一点侧边栏里的索引就会卡住

**Comment by ekibun** [comment]
没能复现。
能不能贴一下手机型号和logcat

**Comment by SilenceContempt** [comment]
![Screenshot_2019-07-18-10-51-20-44](https://user-images.githubusercontent.com/33833347/61426613-93dfbb80-a94d-11e9-948e-d7537714fd63.png)
如何查看logcat？

**Comment by ekibun** [comment]
不知道是不是http://m.6gdown.com/softedupage/m_71589.html
通法是百度下个adb然后adb logcat
能抓到麻烦发到邮箱soekibun@gmail.com

**Comment by ekibun** [comment]
done，终于知道为什么了

**Comment by SilenceContempt** [comment]
感谢

在 2020年2月8日星期六，ekibun <notifications@github.com> 写道：
