### ISSUE TITLE
观看进度查看问题

### ISSUE THREAD

**Issue by Remawater** [ekibun/Bangumi#6]
观看进度，除了 在看 有显示之外，搁置，抛弃之类的都不会显示，就算点进去了也没有，希望能修复一下。

个人希望全部跟在看一样，在外面也能看到自己看到第几话
![ZOrHRx.png](https://s2.ax1x.com/2019/07/18/ZOrHRx.png)

**Comment by ekibun** [comment]
网页版没有的功能app也办不到啊。

**Comment by Remawater** [comment]
好的  希望能修复 放在除了在看列表里的之外

**Comment by Remawater** [comment]
除了放在 在看 中的番剧
其他点进去都显示不了观看进度  剧集状态
![ZjanKg.png](https://s2.ax1x.com/2019/07/18/ZjanKg.png)

希望大佬能修复一下 感谢

**Comment by ekibun** [comment]
这个抓的是ep页的数据，ep页是没有看过信息的，
和详情页混起来集数超过100会很乱，暂时没有做的打算。

**Comment by Remawater** [comment]
> ep页是没有看过信息的，
> 和详情页混起来集数超过100会很乱，暂
好的
