### ISSUE TITLE
能不能把富文本编辑器去除或者变成可选项

### ISSUE THREAD

**Issue by RtYkk** [ekibun/Bangumi#7]
添加图片占用大量输入框空间，还不方便修改。想传一些其他图床的图片[img]图片链接[/img]居然不识别而是把中间那个链接认为是URL，也不知道是bgm的问题还是客户端的问题。本来表情太多一下找不到bgm38在哪里随便点一个改下数字就行。现在也没了…本来那个BBCODE的逻辑还算合理，现在选中一段文字套了BBCODE之后继续打字必须再去取消之前选中的BBCODE…

**Comment by ekibun** [comment]
不会吧。。。我试了下可以啊，是不是符号打成中文符号了。
bgm38也可以直接打(bgm38)呀。
套用格式是按照前一字符的规则来着，那以后加个切换按钮好了。。

![8E31411876A7103AB332EA270439CF4A](https://user-images.githubusercontent.com/20966437/67636753-af743e00-f90e-11e9-86ac-b254e90cd7e8.jpg)
![6F14ACB58132BEDBD22875E90F23DF39](https://user-images.githubusercontent.com/20966437/67636747-a4211280-f90e-11e9-96c9-c2e02fc42ac1.jpg)

**Comment by RtYkk** [comment]
BBCODE大概还是我的使用习惯问题吧…多谢回复
